// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var Belt_Id = require("bs-platform/lib/js/belt_Id.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");

var cmp = Caml_obj.caml_compare;

var SuitComparable = Belt_Id.MakeComparable({
      cmp: cmp
    });

function dealCascades(freeCell) {
  return {
          cards: /* :: */[
            /* :: */[
              {
                suit: /* Hearts */2,
                rank: 0
              },
              /* [] */0
            ],
            /* [] */0
          ]
        };
}

var Command = {
  dealCascades: dealCascades
};

var allSuits = /* :: */[
  /* Clubs */0,
  /* :: */[
    /* Diamonds */1,
    /* :: */[
      /* Hearts */2,
      /* :: */[
        /* Spades */3,
        /* [] */0
      ]
    ]
  ]
];

var emptyFreeCell = {
  cards: /* :: */[
    /* [] */0,
    /* [] */0
  ]
};

exports.SuitComparable = SuitComparable;
exports.allSuits = allSuits;
exports.emptyFreeCell = emptyFreeCell;
exports.Command = Command;
/* SuitComparable Not a pure module */
