// Generated by BUCKLESCRIPT, PLEASE EDIT WITH CARE
'use strict';

var List = require("bs-platform/lib/js/list.js");
var Curry = require("bs-platform/lib/js/curry.js");
var Caml_obj = require("bs-platform/lib/js/caml_obj.js");
var Belt_List = require("bs-platform/lib/js/belt_List.js");
var Pervasives = require("bs-platform/lib/js/pervasives.js");

function feedbackFor(e, a, p) {
  return "Expected: " + (Curry._1(p, e) + ("\nActual: " + (Curry._1(p, a) + "\n")));
}

function assertEqual($staropt$star, printer, expected, actual, description) {
  var cmp = $staropt$star !== undefined ? $staropt$star : Caml_obj.caml_equal;
  var result = Curry._2(cmp, expected, actual);
  var feedback = result || printer === undefined ? undefined : feedbackFor(expected, actual, printer);
  return {
          result: result,
          description: description,
          feedback: feedback
        };
}

function assertEqual$1(expected, actual, description) {
  return assertEqual(undefined, (function (prim) {
                return String(prim);
              }), expected, actual, description);
}

var Int = {
  assertEqual: assertEqual$1
};

function assertEqual$2(expected, actual, description) {
  return assertEqual(undefined, Pervasives.string_of_bool, expected, actual, description);
}

var Bool = {
  assertEqual: assertEqual$2
};

function printAssertion(a) {
  console.log(a.description);
  var match = a.feedback;
  if (match !== undefined) {
    console.log(match);
    return /* () */0;
  } else {
    return /* () */0;
  }
}

function _runSuite(suite) {
  return List.filter((function (a) {
                  return a.result !== true;
                }))(List.flatten(List.map((function (t) {
                        return Curry._1(t, /* () */0);
                      }), suite)));
}

function runSuite(suite) {
  var failingTests = _runSuite(suite);
  var match = List.length(failingTests);
  if (match !== 0) {
    console.log("Failing tests:\n");
    return Belt_List.forEach(failingTests, printAssertion);
  } else {
    console.log("All tests passed.");
    return /* () */0;
  }
}

exports.Int = Int;
exports.Bool = Bool;
exports.assertEqual = assertEqual;
exports.runSuite = runSuite;
/* No side effect */
